---
name: vvvvvvFirst Cron Job
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Generate JSON file during office hours
        run: |
          now=$(TZ=Europe/Amsterdam date +"%H:%M")
          if [[ "$now" > "08:59" && "$now" < "17:01" ]]; then
            echo '{"message": "Generated JSON file"}' > output.json
          else
            echo "yes" > output.txt
          fi
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v1.2
          release_name: Release v1.2
          body: |
            This is the first release
          draft: false
          prerelease: false
      - name: Upload file as release asset
        uses: actions/upload-release-asset@v1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output.json
          asset_name: output.json
          asset_content_type: application/json
